-- Create a table to store resumes
create table resumes (
  id bigint generated by default as identity primary key,
  content jsonb,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
-- For development simplicity, we are allowing public access. 
-- IN PRODUCTION: You should enable RLS and restrict access to authenticated users.
alter table resumes enable row level security;

create policy "Enable all access for all users"
on resumes for all
using (true)
with check (true);
